[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

; Thư viện cần cài (PubSubClient cho MQTT)
lib_deps =
    knolleary/PubSubClient@^2.8

; Serial monitor baud rate
monitor_speed = 115200

; Tốc độ nạp (giảm xuống 460800 nếu bị lỗi upload)
upload_speed = 921600

; Bỏ comment dòng dưới nếu muốn chỉ định cổng COM cụ thể
; upload_port = COM3
; monitor_port = COM3

build_flags =
    -DCORE_DEBUG_LEVEL=0
