@startuml
skinparam defaultTextAlignment center
skinparam maxMessageSize 150
skinparam roundCorner 8
skinparam backgroundColor white

node "Power Supply" as battery
node "ESP32" as esp32
node "SIM7600 Module\n(GPS + 4G LTE)" as sim7000g

component "BOOT Button\n(GPIO0 - SOS)" as sos
component "GPS Antenna" as ant_gps
component "GSM Antenna" as ant_gsm

battery --> esp32 : Power
battery --> sim7000g : Power
esp32 <--> sim7000g : UART2
sos --> esp32 : FALLING interrupt\n(active LOW)
ant_gps --> sim7000g : GPS signal
ant_gsm --> sim7000g : GSM signal

@enduml
